# Generated by Django 6.0.5 on 2026-05-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('platform_post_url', models.URLField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='blog.post')),
            ],
            options={
                'ordering': ['-posted_at'],
                'unique_together': {('post', 'platform')},
            },
        ),
    ]
