# Generated by Django 6.0.5 on 2026-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_socialpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('threads', 'Threads'), ('quora', 'Quora')], max_length=20),
        ),
    ]
