# Generated by Django 6.0.4 on 2026-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='', help_text='Used for SEO meta description. Keep under 160 characters.', max_length=160),
            preserve_default=False,
        ),
    ]
