# Generated by Django 6.0.4 on 2026-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first (1, 2, 3, etc.)'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check to display this post in the hero section'),
        ),
    ]
