# Generated by Django 6.0.5 on 2026-05-18 19:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='SocialPost',
        ),
    ]
