# Generated by Django 6.0.5 on 2026-05-20 03:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content_alter_staticpage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
