# Generated by Django 6.0.4 on 2026-05-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X / Twitter'), ('threads', 'Threads')], max_length=20)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('failed', 'Failed')], max_length=20)),
                ('platform_post_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='blog.post')),
            ],
            options={
                'ordering': ['-posted_at'],
                'unique_together': {('post', 'platform')},
            },
        ),
    ]
